/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

int main(void)
{
    long long myLongHistory = 900;

    char size = sizeof(myLongHistory);

    printf("Size of char data type %d\n", sizeof(char));
    printf("Size of short data type %d\n", sizeof(short));
    printf("Size of int data type %d\n", sizeof(int));
    printf("Size of long data type %d\n", sizeof(long));
    printf("Size of long long variable %d\n", size);

	for(;;);
}
