/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Address of RCC clock control register (AHB1ENR)
 * 0x40023800 + 0x30
 *
 * Address of GPIOA mode register (used to control mode)
 * 0x4002 0000 + 0x00
 *
 * Address of GPIOA output data register (used to write)
 * GPIOx_ODR -> 0x4002 0000 + 0x14
 *
 */
#include <stdint.h>


int main(void)
{

    uint32_t *pRCC_ControlReg = (uint32_t*)0x40023830;
    uint32_t *pGPIOA_ModeReg = (uint32_t*)0x40020000;
    uint32_t *pGPIOA_OutputDataReg = (uint32_t*)0x40020014;

    /* GPIOA peripheral clock enabled for Port A */
    *pRCC_ControlReg |= 0x01;

    /* GPIOA mode register set. Pin 5 */
    *pGPIOA_ModeReg &= 0xFFFFF9FF;
    *pGPIOA_ModeReg |= 0x00000600;

    /* GPIOA Data register set/ Set 5th bit to turn on LD2 */
    *pGPIOA_OutputDataReg |= 0x20;

	for(;;);
}
